#document settings

title: Draft Grants Management Data Standards Feedback 
desc: "Collaboration Space"
url: grantsfeedback.cfo.gov
repo_name: federalfinancialmanagement
branch: master
encoding: utf-8

#global settings, no need to change these
root_url: //fedfmdataelements.github.io
org_name: fedfmdataelements

# default build settings for running locally, no need to edit
highlighter: rouge
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "LICENSE"]
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: []
relative_permalinks: false

gems:
 - jekyll-redirect-from

whitelist:
 - jekyll-redirect-from

navigation:
 - title: Home
   url: /index.html


sass:
  sass_dir:          assets/_scss
  #style:            :compressed
